"""update unique rull for user_radio

Revision ID: 2f229bb3594a
Revises: 73e1a1b6cf05
Create Date: 2025-03-28 23:26:26.062748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f229bb3594a'
down_revision: Union[str, None] = '73e1a1b6cf05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_radio', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_inter_model', ['user_id', 'radio_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_radio', schema=None) as batch_op:
        batch_op.drop_constraint('unique_inter_model', type_='unique')

    # ### end Alembic commands ###
