"""create M:M link

Revision ID: 73e1a1b6cf05
Revises: a7135794b44d
Create Date: 2025-03-22 13:09:40.035961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73e1a1b6cf05'
down_revision: Union[str, None] = 'a7135794b44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('radio',
    sa.Column('source', sa.String(length=250), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('source')
    )
    op.create_table('user_radio',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('radio_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['radio_id'], ['radio.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_radio')
    op.drop_table('radio')
    # ### end Alembic commands ###
